apiVersion: v1
kind: Service
metadata:
  name: cd-docker-project-service
spec:
  selector:
    app: cd-docker-project
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
