name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t nguyenminhhieu2k/cd_docker_project:latest .
      - name: Log in to Docker Hub
        run: echo '${{ secrets.Hieunam2205 }}' | docker login -u '${{ secrets. nguyenminhhieu2k }}' --password-stdin
      - name: Push Docker image to Docker Hub
        run: docker push nguyenminhhieu2k/cd_docker_project:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.192.168.0.239}}'
          username: '${{ secrets.macbook}}'
          key: '${{ secrets.220500 }}'
          script: |
            cd /path/to/project
            docker-compose pull
            docker-compose down
            docker-compose up -d

